### PR TITLE
Add dpkg-buildpackage log to .gitignore

### PR DESCRIPTION
**Pull request by leeclemens**

### CODE REVIEW

**Comment by mutability** [comment]
I don't get this left behind after a clean build (dpkg-buildpackage -b -tc)

**Comment by leeclemens** [comment]
Perhaps it wasn't cleaned up after a clean build with `dpkg-buildpackage -b`.  Should `-tc` be added to the [Building from source](https://github.com/mutability/dump1090#building-from-source) example (not sure if that would clean it up in addition to the other debhelper files - I'm sure I would have included them)?

Having issues doing a clean build at the moment or I would try to check it myself.

**Comment by mutability** [comment]
I either get many debhelper / package build artifacts that are not covered by .gitignore, or none - I don't see a middle ground. I think it's OK as is, you can always git clean -ix or debian/rules clean?

**Comment by leeclemens** [comment]
Did you try a failed build with only `-b` and then a clean one also with only `-b`? That is what I followed from the readme.

**Comment by mutability** [comment]
I don't understand what you're asking. If I build with -b then I get a dirty tree. If I build with -b -tc, or if I do a debian/rules clean in a dirty tree, then I get a clean tree. This PR doesn't change that as it only handles one file that's generated, not all of them. I don't know if it is worth trying to handle all the files in .gitignore since there is an obvious way to avoid the problem - clean the tree.

**Comment by leeclemens** [comment]
[Building from source](https://github.com/mutability/dump1090#building-from-source) says to use `-b`, not `-b -tc`. I understand from what you are saying that `-tc` prevents this file from being left behind.

Should the readme recommend using `-b -tc` ? (Please forgive me as I'm not experienced with dpkg...is there a reason not to always use `-tc`?)

**Comment by mutability** [comment]
There's no harm in building either way.

**Comment by leeclemens** [comment]
So building with `-b` leaves this file behind, building with -`b -tc` cleans it up, should the readme be updated? Obviously that would be a different PR, but your comments beg the question.

**Comment by mutability** [comment]
Building with -b builds the package, which produces intermediate files of which the logfile is one.
Building with -b -tc builds the package as with -b, then removes the intermediate files afterwards (literally by running debian/rules clean)

Which one you pick depends on whether you care about the intermediate files.
Why do you care about the intermediate files?
The readme looks fine to me.

**Comment by leeclemens** [comment]
My reasoning is: the readme says to use -b, which leaves this file behind. So I suggested adding it to .gitignore (so it wouldn't be in git status).
You don't run in to this issue because you run -b -tc, which cleans the file and it of course does not appear in git status.

I don't care about the intermediate file, which is why I suggested either adding it to .gitignore or recommending (the readme) users use -b -tc.

**Comment by mutability** [comment]
But your PR does not fix this, there are many more intermediate files, not
just the one you added.

I don't think it is worth the effort to try to put every possible
intermediate file in gitignore. To get a clean tree, use the existing tools
that are designed to give you a clean tree.

**Comment by leeclemens** [comment]
That was the only one I experienced.

As someone unfamiliar with building packages to Debian, I was not aware of the -tc option - which is why I suggested it could be added to the readme after you brought it up.

Just trying to help.

**Pull request closed without merging**
