### PR TITLE
Update Debian init script to require $network - Issue #172

### PR DESCRIPTION
**Pull request by Romeo-Golf**
Update Debian init script to require $network and $local_fs - Issue #172

### CODE REVIEW

**Comment by mutability** [comment]
The $local_fs dependency is pointless, it is implied by $remote_fs

(... so you need to remove that change)

**Comment by Romeo-Golf** [comment]
I did consider that, but figured as it didn't result in any additional lines of code being changed it was better to be safe than sorry...

Also the standard doesn't seem to agree, implied or otherwise, I would not expect the following wording if that was indeed the case (my emphasis):

> Many applications that require $local_fs will probably **also** require $remote_fs.

**Comment by mutability** [comment]
https://wiki.debian.org/LSBInitScripts

> Scripts depending on $remote_fs do not need to depend on $local_fs.

fixitfixitfixit

**Comment by mutability** [comment]
> I would not expect the following wording

`If A then B` does not imply `if B then A`

**Comment by Romeo-Golf** [comment]
From what I can see the description at https://wiki.debian.org/LSBInitScripts referred to Debian's interpretation and implementation of the standards, which as we have seen from the subtle but similar difference in their interpretation of $network can cause platforms which cannot run a pure Debian release.

Having double checked the latest LSB spec version 5 it appears their definition is unchanged from the one you link to earlier:

http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/facilname.html

>$remote_fs	 	
>     all remote file systems are available. In some configurations, file systems such as /usr may be remote. Many applications that require $local_fs will probably also require $remote_fs.

However the original version 1.0.0 , was arguably less ambiguous, has this definition:

http://refspecs.linuxfoundation.org/LSB_1.0.0/gLSB/facilname.html

>$remote_fs
>	all remote filesystems are mounted (note in some cases /usr may be remote. Most applications that care will probably require both $local_fs and $remote_fs)

And without getting into a debate about causality, _my interpretation_ of the line in question is that were $remote_fs to explicitly require all local file systems to be mounted then it would have been worded as:

>$remote_fs
> all **local and remote** file systems are available. In some configurations, file systems such as /usr may be remote. Many applications that require $local_fs will probably require $remote_fs **instead**.

**Comment by mutability** [comment]
That's nice but I said I would take a PR that added $network as the minimal change, and that is not what this PR does. If you want to update the PR to do the minimal change, great. If you don't want to do that then it will stay unmerged.

**Comment by Romeo-Golf** [comment]
ok your call, I will revise this PR and submit another to suggest making the init script follow the explicit rather than implicit definitions of the LSB definitions ;)

**Comment by mutability** [comment]
Given that the initscript targets Debian and is not tested anywhere else I'm fine with following the Debian docs (up until someone demonstrates a system where that interpretation breaks)

**Comment by Romeo-Golf** [comment]
cheers, seems like a reasonable compromise to hopefully resolve the reported issue and address the subtle differences between the explicit and implicit interpretations if/when it causes issues :)

**Pull request merged**
