### PR TITLE
Allow the sidebar to shrink its height

### PR DESCRIPTION
**Pull request by tslocum**
I've tested these changes on Chrome, Firefox and Internet Explorer 11.  In addition to the sidebar changes I've added a DOCTYPE declaration and set a fixed width on the flag column.

newmap

### CODE REVIEW

**Comment by mutability** [comment]
This seems to have lost the spacing between the table rows (I think it's an improvement, actually, but I wonder if it was intentional or not)

**Comment by mutability** [comment]
Also, this appears to lose the map zoom controls under the table if the table is large enough to take up the full height, which is a problem..

**Comment by tslocum** [comment]
Thanks for reviewing.  The removal of the spacing was indeed intentional.  I've updated the pull request to move the zoom controls to the bottom left.

**Comment by mutability** [comment]
Hmm. I'm not 100% sure about letting the map spread behind the table. It adds some odd behaviour since the map is actually spanning the whole width behind the table, e.g. centering on a plane doesn't actually horizontally center it in the visible part of the map any more, and the attribution info on the map gets clobbered by the table. I wonder if this can be compensated for.

For the cases where you want to make better use of the righthand side, I'm leaning more towards the other approach (seen in #58) of adding something to hide the table on demand.

What do you think?

**Pull request closed without merging**
