### PR TITLE
Allow web access to json directory

### PR DESCRIPTION
**Pull request by dschaper**
Update url alias to point to data directory and allow for directory listing of json files. Remove superfluous redirect rule for gmap.html. Update url alias right hand side for trailing backslash (per lighttpd alias suggestions.)

### CODE REVIEW

**Comment by mutability** [comment]
Why's it useful to have a directory listing here?

**Comment by dschaper** [comment]
So the files could be access via web browser. May not be really too useful, but it allows a user to see which json files are being produced and the data in them without needing to pull up the readme or a data dictionary.

**Comment by mutability** [comment]
Maybe handy for development, but not something I'd really want in the default package config. You can just look directly in the data dir..

**Comment by dschaper** [comment]
Fair enough. Is there a reason for the name gmap.html instead of index.html?

**Comment by mutability** [comment]
No reason, that's just what it was originally called

**Comment by dschaper** [comment]
Okay, I'll close this out then.

**Pull request closed without merging**
