### PR TITLE
Merge planes db/jsons with basestation.sqb and vrs.sqb

### PR DESCRIPTION
**Pull request by kentrosaur**
Compared the vrs & basestation(mantma.co.uk) databases and merged
any airframes which had icao type codes and tail numbers.

### CODE REVIEW

**Comment by mutability** [comment]
Can you document the process you used to merge this data and the exact
source of the data.

**Comment by kentrosaur** [comment]
I can be more specific on the procedure later if necessary.  It was mostly `sqlite3 'select modes from aircraft'` then compared the lists and merged them to a common database.  The json was generated from the tools/vrs-basicaircraft-to-json.py modified to use the other sqb.

The original mantma source was: http://www.mantma.co.uk/pp_support.html but has been withdrawn as of 03 March 2015
This database was also augmented by the FAA registry:
https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download/

**Comment by mutability** [comment]
I am a little reluctant to use the mantma DB if they have withdrawn it; what were the redistribution permissions on that DB and what's the reliability of the data like?

Merging the FAA data sounds like a good idea, I think that is all public record. Can you contribute your changes to the tools so that can be rerun periodically?

**Comment by kentrosaur** [comment]
Understood from that angle.  It's a year out of date but still more info on non-us flights than I have found elsewhere.  I got permission from the old dbadmin at mantma to re-use the contents in dump1090 since it's abandonment.  It was pretty reliable as it matched hex-codes and airframe serial numbers to avoid duplication. (there were lots of ownership transfers month to month!)

I've been meaning to write a new tool to work with the FAA database.  I've only run it to add airframes not present in my database after seeing them.  It's a bit of a headache as they don't use ICAO type codes automatically so I've made a mapping to get from the hex code to a usable airframe.  I'm going to aim to make a complete FAA database shortly so I'll keep you posted there.

The other interesting thing might be to update the icaooperator (baw,dlh,aal etc) Again, this is another mapping job needed for the script.  Most of these are present in the mantma db but weren't a requirement.

Is there any anticipated return of the --aggressive mode?

**Comment by mutability** [comment]
I wonder if the thing to do here is to make it a little easier to regenerate the json, then let people plug in their own data. (That was always the intention, but it's not particularly easy to do right now). I don't really want to start maintaining the DB myself..

**Comment by mutability** [comment]
Re --aggressive, you can enable this at build time but I do not see it coming back in the previous form any time soon. It produces a few additional messages, but it also produces a lot of incorrect messages that are indistinguishable (at a simple level) from real messages. If you are doing anything except using the data locally, this is not worth the tradeoff. In practice way too many people were turning it on without understanding the consequences and causing all sorts of problems for aggregation sites.

One possible option would be to never forward data that resulted from 2-bit correction. Alternatively, forcing --net-verbatim when --aggressive was used might work as this pushes the responsibility for correction to the recipient. Would those fit your use case (what's your use case?).

**Comment by kentrosaur** [comment]
My usage has been personal only so any bogus messages it would give me weren't a big deal.  Thanks for re-enabling that with the fix, it's good to have.  I've been meaning to look more at the standard --fix since I was watching a plane bounce between 45000' and 120000' a few days ago but didn't have time to investigate.

The FAA-> ICAO database mapping is quite a headache and likely needs a lot of maintenance since the ACFTREF is being updated constantly.  The major commercial airframes are relatively easy to get but the sheer number of general aviation items are a mess.  The sqlite3 version of this is also pretty slow to query at 300MB.  Given the difficulty in assembling this, it's not a surprise there is a market for commercial databases for registrations.

The script was easy enough to port to the basestation.sqb so I might just add that to the tools and add a readme on how to merge the databases.  Distributing an extra 4mb of text isn't really beneficial.  

On a similar thread, I've made the flags.js into a json file which is a little more portable for lookups.  Do you have any interest in that?

**Pull request closed without merging**
