### PR TITLE
Fix DB JSON 404, fix favicon 404 by adding one

### PR DESCRIPTION
**Pull request by toofishes**
This fixes the two 404 errors that show up in my nginx logs. Add a super-simple stub empty JSON file for the non-ICAO addresses, and build a simple favicon derived from the default airplane image used on the map.

favicon example

```
nginx[28910]: 2016/10/15 14:16:20 [error] 28914#28914: *16457 open() "/usr/share/dump1090-mutability/html/favicon.ico" failed (2: No such file or directory), server: localhost, request: "GET /favicon.ico HTTP/1.1"
nginx[28910]: 2016/10/15 14:16:26 [error] 28914#28914: *16455 open() "/usr/share/dump1090-mutability/html/db/~.json" failed (2: No such file or directory), server: localhost, request: "GET /db/~.json HTTP/1.1"
```

### CODE REVIEW

**Comment by mutability** [comment]
Think I'd prefer to mask the request for ~.json so it never happens in the first place

**Comment by toofishes** [comment]
That is fair. I'm working on a fix for #149 and can incorporate a fix in there.

**Comment by toofishes** [comment]
@mutability - updated the PR here to reflect your thoughts, as well as fully fixing #149. There is no more stub `~.json` file anymore. Let me know what you think.

**Comment by toofishes** [comment]
Thoughts here?

**Comment by mutability** [comment]
Looks good from a quick look. Can you break out the nodejs tweaks?

**Pull request closed without merging**
