### PR TITLE
Web UI: parallel loading of history (speed up)

### PR DESCRIPTION
**Pull request by smartynov**
I noticed that html page takes a lot of time to load, primarily caused by sequential requests for loading history. I propose this patch to enable loading history in parallel, which results in significant speed up of page loading time. We just start all requests using jquery and let the browser handle concurrency. Chrome allows for 4 concurrent requests, some older browsers may allow 2, but no browser will run all the request at once, so server-side will be safe.

### CODE REVIEW

**Comment by smartynov** [comment]
P.S. I have no idea why checks failed, it seems to be unrelated to my changes

**Comment by OrbitTheSun** [comment]
A very noticeable speed up. - Thank you for this improvement!

**Comment by smartynov** [comment]
Closing to re-open (hope it will pass test now)

**Comment by smartynov** [comment]
The test environment seems to be broken for this project, failing in C code build... As I see no changes in javascript file since last year, I still think it is a good idea to accept this PR.

**Pull request closed without merging**
