### PR TITLE
Redesigned web interface

### PR DESCRIPTION
**Pull request by kazazes**
I rewrote the existing HTML with Bootstrap and a dark color scheme and a vertical split. I replaced the existing markup with Bootstrap equivalents throughout and kept the underlying element bindings intact.  See demo at http://home.peterk.co:8080. 

dump-mobile

### CODE REVIEW

**Comment by kazazes** [comment]
Added data-history charts and rebased on current master. Demo is up at http://home.peterk.co:8080.
screen shot 2015-12-03 at 11 00 09

**Comment by mutability** [comment]
This looks pretty slick! A few initial comments.

There's lots of changes that are just reindenting/reformatting - let's do those separately.

I may drop the changes to the default colors & map type. It might make sense to tie those to the map type, though that's a bit more work.

The positioning of the aircraft list is a bit awkward, I find myself scrolling back and forth between the list and the map a lot. I wonder if there is a better way to lay that out.

**Comment by kazazes** [comment]
@mutability, I'll change the dark map to an option and default to the original and revert the indentations and move them to a separate commit. 

Regarding the list placement, I think it would be best if I made the info view collapsable. The aircraft table would get brought up by a few hundred pixels.

**Comment by caiusseverus** [comment]
I much prefer the aircraft list on the right rather than below. On a widescreen display, it makes the map rather narrow (especially on a lower resolution laptop screen). There is also quite a bit of dead space either side of the aircraft list with it below. The graphs are a very nice addition.

**Comment by anish** [comment]
@kazazes fyi, demo seems down. Is this abandoned ?

**Comment by kazazes** [comment]
@anish, not abandoned, just took that server offline. [See my fork](https://github.com/kazazes/dump1090/tree/master/public_html). I did make the modifications suggested by @caiusseverus but haven't pushed them yet.

**Comment by mutability** [comment]
Don't think this one is going anywhere.

**Comment by kazazes** [comment]
It's all in my fork, see the original PR.

**Pull request closed without merging**
