### PR TITLE
make building with debug symbols optional

### PR DESCRIPTION
**Pull request by labomb**
Use 'make DEBUG=1' if they are needed.

### CODE REVIEW

**Comment by mutability** [comment]
Why?

**Comment by labomb** [comment]
A couple of reasons... with '-g' the resulting executables are somewhere around 3x to 4x larger than they need to be (yes, they can be stripped after... but why the extra step?). In addition, it will interfere with most optimization flags if one wishes to pass them at build time.

**Comment by mutability** [comment]
The stripping happens as part of the standard debian package build.

-g does not interfere with optimization.

**Comment by labomb** [comment]
I wasn't aware that everyone uses the standard debian package build, and not the Makefile directly.

Re. optimization, perhaps 'some optimizations' would have been more accurate. Either way, I'll respectfully disagree and close the PR.

**Comment by mutability** [comment]
No, seriously, I know of no case where -g affects the code emitted by gcc. Do you have an example where it does?

You don't have to use the debian package but I assume that if you are worried about executable size then you are building a binary package of some type, at which point you should use the package manager's tools for handling debug symbols. (I think in the redhat world, you can split off "debuginfo" rpms).

Debug symbols are so useful, even in nominally release builds, that you need a very strong argument for dropping them.

**Comment by mutability** [comment]
BTW, I just built dump1090 twice, with and without -g, and objdumped the .text sections of the resulting files. They are byte-for-byte identical.

**Comment by labomb** [comment]
Re. package managers, I don't always use them, nor do I always have the option. In this case.. a simple 'git clone', followed by 'cd dump1090', followed by 'make' gives me what I need (albeit significantly larger) for testing purposes in less than 20 seconds. I'd venture a guess that I'm not the only one who frequently grabs sources, builds, and hacks in this manner.

Re. optimization, there are myriad of reference points out there, but a couple can be found [here](https://books.google.com/books?id=OwMsCwAAQBAJ&pg=PT992&lpg=PT992&dq=gcc+%22-g%22+optimization+conflicts&source=bl&ots=agFanB9Mux&sig=HJLo0HysqR4lRyBXLHp1-tO4Ans&hl=en&sa=X&ved=0ahUKEwjhyZX7pI3SAhVL12MKHZr-DBoQ6AEITzAI#v=onepage&q=gcc%20%22-g%22%20optimization%20conflicts&f=false) and [here](http://stackoverflow.com/questions/89603/how-does-the-debugging-option-g-change-the-binary-executable).

And while I may agree that debug symbols can indeed be so useful **when needed**, as you mentioned even the standard debian package build strips them out. I see no reason to make them the default in the Makefile. If a user does wish to debug (as I have), there are many debug options other than '-g' that may well be more preferable.

**Comment by mutability** [comment]
If you're not using a package manager then I assume you're capable of stripping on install. The "install" program even has an option to do it for you. And you are talking about 500kB vs 130kB; unless you're installing on an embedded target, it really really really doesn't matter in today's environment where having 1TB of available storage is on the small side.

It is hugely useful to have debug symbols so that when an end user sees a crash I can give them instructions on how to get a useful stacktrace out of it.

The first optimization link you gave says that turning on optimization with -g makes debugging harder, not that adding -g makes optimization worse.

The second link talks about how some compilers disable optimizations when -g is used. gcc is not one of those compilers.

I would take a patch that let you disable -g if you explicitly asked for it. (You can already do that by overriding CFLAGS on the command line). But the default must be to include debugging info.

**Pull request closed without merging**
