### PR TITLE
Autoload Terrain Option

### PR DESCRIPTION
**Pull request by m30164**
Added autoload terrain option. You can enable or disable automatic
switching to terrain view for the default google map view.

(Smaller pull request instead of a single big one)

### CODE REVIEW

**Comment by m30164** [comment]
Premature pull request, will fix later, sorry for the spam ^^

**Comment by mutability** [comment]
BTW, you can update pull requests by committing more things to the same branch - they'll automagically get added to the request.

**Comment by m30164** [comment]
Hmhm, that was what happened while I didn't want it to do so. because now you can decide what to pull from the separate branches. (that should be easier for you right?)

**Comment by mutability** [comment]
Yeah. You should have one branch per pull request :)

**Pull request closed without merging**
