### PR TITLE
Record the positions to create a heat map

### PR DESCRIPTION
**Pull request by rgeissert**
(n.b. this was done before I noticed the `heatmap` branch)

This changeset adds a fairly limited heatmap based on the latest 20000 positions. From a quick look at the original `heatmap` branch:
- uses an Array, and a refresh interval of 5 seconds
- adds a way to display and hide the heat map; probably not at the best place of the page
- it only records a position for a given plane if it differs from its previous position

The arbitrary limit should probably be configurable, and/or time-based.

What do you think?

### CODE REVIEW

**Comment by mutability** [comment]
That looks like a reasonable approach. I'll try to find some time to play with this.

**Comment by leeclemens** [comment]
+1  Been running with this for a few hours, seems functional (rebased with master, switched between maps). RPi B+ with ~90 messages/sec and ~20 aircraft seen at any given time.

**Comment by rgeissert** [comment]
The radius should probably be configurable and/or perhaps automatically reduce it over time based on the number of positions recorded.

I've drafted some code to store the positions history in the browser's localStorage so that one can close the web interface and come back later without loosing a lot of data. It tries to do some deduping between the data stored in localStorage and the data from PositionHistoryBuffer, but the timestamps do not seem to match.

If this is of any interest to anyone just let me know and I'll push it to another branch.

**Comment by Romeo-Golf** [comment]
Yes this could be interesting.. :)

**Pull request closed without merging**
